services:
  inventree-db:
    image: postgres:15
    environment:
      POSTGRES_DB: inventree
      POSTGRES_USER: inventree
      POSTGRES_PASSWORD: inventree
    volumes:
      - inventree-db:/var/lib/postgresql/data

  inventree-server:
    image: inventree/inventree:stable

    depends_on:
      - inventree-db
    ports:
      - "1337:8000"
    volumes:
      - ./data:/home/inventree/data
    environment:
      INVENTREE_DB_ENGINE: django.db.backends.postgresql
      INVENTREE_SITE_URL: http://localhost:1337
      INVENTREE_DB_NAME: inventree
      INVENTREE_DB_USER: inventree
      INVENTREE_DB_PASSWORD: inventree
      INVENTREE_DB_HOST: inventree-db
      INVENTREE_DB_PORT: 5432

volumes:
  inventree-db:
  inventree-data:
